// data/placeholders.ts - UPDATED VERSION
import { 
  VerdictData, 
  VerdictResult,
  MetricScore,
  MetricBreakdown,
  SubMetric,
  MetricFlag,
  Evidence 
} from '@/types';

// Updated metric weights for the 13-metric framework
export const METRIC_WEIGHTS = [
  { key: 'team_identity', name: 'Team Identity', weight: 13 },
  { key: 'team_competence', name: 'Team Competence', weight: 11 },
  { key: 'contaminated_network', name: 'Contaminated Network', weight: 19 },
  { key: 'mercenary_keywords', name: 'Mercenary Keywords', weight: 9 },
  { key: 'message_time_entropy', name: 'Message Time Entropy', weight: 5 },
  { key: 'account_age_entropy', name: 'Account Age Entropy', weight: 5 },
  { key: 'tweet_focus', name: 'Tweet Focus', weight: 7 },
  { key: 'github_authenticity', name: 'GitHub Authenticity', weight: 10 },
  { key: 'bus_factor', name: 'Bus Factor', weight: 2 },
  { key: 'artificial_hype', name: 'Artificial Hype', weight: 5 },
  { key: 'founder_distraction', name: 'Founder Distraction', weight: 6 },
  { key: 'engagement_authenticity', name: 'Engagement Authenticity', weight: 10 },
  { key: 'tokenomics_red_flags', name: 'Tokenomics Red Flags', weight: 7 },
];

interface RawMetricInput {
  key: string;
  name: string;
  value: string | number;
  score: number;
  subline?: string;
  details?: string;
  flags?: string[];
}

function getVerdict(score: number): VerdictResult {
  if (score >= 70) return 'reject';
  if (score >= 40) return 'flag';
  return 'pass';
}

function getRiskSummary(score: number): string {
  if (score >= 80) return 'Critical risk: Multiple critical red flags indicating high probability of scam';
  if (score >= 60) return 'High risk: Significant concerns requiring careful manual review';
  if (score >= 40) return 'Moderate risk: Mixed signals, needs further investigation';
  if (score >= 20) return 'Low risk: Generally positive indicators with minor concerns';
  return 'Very low risk: Strong fundamentals across all metrics';
}

function generateMockMetricScore(score: number, metricName: string): MetricScore {
  const status = score >= 80 ? 'critical' : score >= 60 ? 'high' : score >= 40 ? 'moderate' : 'low';
  
  const subMetrics: SubMetric[] = [
    { name: 'Sub-metric A', score: Math.max(0, score - 10), weight: 25, description: 'Primary assessment factor' },
    { name: 'Sub-metric B', score: Math.min(100, score + 5), weight: 25, description: 'Secondary validation factor' },
    { name: 'Sub-metric C', score: Math.max(0, score - 5), weight: 25, description: 'Quality check factor' },
    { name: 'Sub-metric D', score: Math.min(100, score + 10), weight: 25, description: 'Cross-reference factor' },
  ];

  const breakdown: MetricBreakdown = {
    subMetrics,
    weightedScore: score,
    calculationDetails: `Weighted average of ${subMetrics.length} sub-metrics for ${metricName}`
  };

  const flags: MetricFlag[] = [];
  if (score >= 70) {
    flags.push({
      severity: 'critical',
      description: 'Critical risk detected in this metric',
      evidence: ['Automated detection', 'Pattern matching'],
      recommendation: 'Requires immediate attention'
    });
  } else if (score >= 50) {
    flags.push({
      severity: 'high',
      description: 'Elevated risk signals detected',
      evidence: ['Statistical analysis', 'Threshold crossing'],
      recommendation: 'Further investigation recommended'
    });
  }

  const evidence: Evidence[] = [
    {
      type: 'url',
      source: 'Automated Analysis',
      url: '#',
      timestamp: new Date(),
      confidence: 85,
      description: 'Generated by Sifter analysis engine'
    }
  ];

  return {
    score,
    confidence: Math.min(95, 70 + Math.random() * 25),
    status,
    breakdown,
    flags,
    evidence
  };
}

function buildVerdictData(
  projectName: string,
  input: string,
  rawMetrics: RawMetricInput[]
): VerdictData {
  // Calculate composite score
  let totalScore = 0;
  let totalWeight = 0;

  rawMetrics.forEach(metric => {
    const weightInfo = METRIC_WEIGHTS.find(w => w.key === metric.key);
    const weight = weightInfo?.weight || 0;
    totalScore += metric.score * weight;
    totalWeight += weight;
  });

  const riskScore = Math.round(totalScore / totalWeight);
  const verdict = getVerdict(riskScore);
  const summary = getRiskSummary(riskScore);
  const confidence = Math.min(95, 75 + Math.random() * 20);
  const processingTime = Math.floor(Math.random() * 60000) + 30000; // 30-90 seconds

  // Generate recommendations based on score
  const recommendations: string[] = [];
  if (riskScore >= 80) {
    recommendations.push('🚨 IMMEDIATE REJECTION: Multiple critical red flags detected');
    recommendations.push('🔴 High probability of scam based on historical patterns');
    recommendations.push('⚠️ Connected to known bad actors in our database');
    recommendations.push('📉 Artificial community and coordinated messaging detected');
  } else if (riskScore >= 60) {
    recommendations.push('⚠️ Proceed with extreme caution');
    recommendations.push('🔍 Requires manual review by investment committee');
    recommendations.push('📊 Multiple concerning signals need verification');
    recommendations.push('💬 Community health requires attention');
  } else if (riskScore >= 40) {
    recommendations.push('🟡 Moderate risk - standard due diligence required');
    recommendations.push('📈 Some positive signals but needs monitoring');
    recommendations.push('👥 Team identity verification recommended');
    recommendations.push('📋 Additional technical review advised');
  } else if (riskScore >= 20) {
    recommendations.push('🟢 Low risk - appears legitimate');
    recommendations.push('✅ Passes majority of safety checks');
    recommendations.push('🎯 Standard investment protocol applicable');
    recommendations.push('📊 Continue routine monitoring');
  } else {
    recommendations.push('✅ Very low risk - strong fundamentals');
    recommendations.push('🎯 Ideal candidate for investment');
    recommendations.push('🏆 Excellent across all major metrics');
    recommendations.push('📈 Strong growth potential indicated');
  }

  // Generate detailed metrics array
  const detailedMetrics: MetricScore[] = rawMetrics.map(metric => 
    generateMockMetricScore(metric.score, metric.name)
  );

  return {
    projectName,
    riskScore,
    verdict,
    confidence,
    processingTime,
    summary,
    recommendations,
    detailedMetrics
  };
}

// HIGH RISK (REJECT) EXAMPLE - MoonDoge Protocol
const rejectRawMetrics: RawMetricInput[] = [
  {
    key: 'team_identity',
    name: 'Team Identity',
    value: 72,
    score: 72,
    subline: '2/5 team members anonymous',
    flags: ['Partially anonymous team', 'Limited professional profiles']
  },
  {
    key: 'team_competence',
    name: 'Team Competence',
    value: 45,
    score: 45,
    subline: 'Limited GitHub activity, poor documentation',
    flags: ['No verifiable experience', 'Poor documentation quality']
  },
  {
    key: 'contaminated_network',
    name: 'Contaminated Network',
    value: 93,
    score: 93,
    subline: 'Agency "CryptoGrowth Labs" - 60% failure rate',
    flags: ['Connected to known rug agency', '3 confirmed rug pulls by same agency']
  },
  {
    key: 'mercenary_keywords',
    name: 'Mercenary Keywords',
    value: 87,
    score: 87,
    subline: '71% mercenary, 8% genuine, 20% technical',
    flags: ['Extreme financial extraction focus', 'Minimal genuine community discussion']
  },
  {
    key: 'message_time_entropy',
    name: 'Message Time Entropy',
    value: 82,
    score: 82,
    subline: '47% of messages between 2-4 AM UTC',
    flags: ['Bot-like posting patterns', 'Coordinated messaging detected']
  },
  {
    key: 'account_age_entropy',
    name: 'Account Age Entropy',
    value: 78,
    score: 78,
    subline: '52% accounts created in same week',
    flags: ['Bulk account creation', 'Sybil attack patterns']
  },
  {
    key: 'tweet_focus',
    name: 'Tweet Focus',
    value: 34,
    score: 34,
    subline: 'Consistent messaging, focused narrative',
    flags: ['Overly consistent messaging', 'Potential scripted content']
  },
  {
    key: 'github_authenticity',
    name: 'GitHub Authenticity',
    value: 65,
    score: 65,
    subline: 'Forked repo, limited original code',
    flags: ['Copied codebase', 'Limited original development']
  },
  {
    key: 'bus_factor',
    name: 'Bus Factor',
    value: 78,
    score: 78,
    subline: 'Single point of failure identified',
    flags: ['High dependency on single contributor', 'Low contributor diversity']
  },
  {
    key: 'artificial_hype',
    name: 'Artificial Hype',
    value: 71,
    score: 71,
    subline: 'Follower spike detected',
    flags: ['Paid growth campaigns', 'Inorganic engagement']
  },
  {
    key: 'founder_distraction',
    name: 'Founder Distraction',
    value: 23,
    score: 23,
    subline: 'Focused, no concurrent projects',
    flags: ['Healthy founder focus', 'No concerning distractions']
  },
  {
    key: 'engagement_authenticity',
    name: 'Engagement Authenticity',
    value: 76,
    score: 76,
    subline: 'High copy-pasta rate, low thread depth',
    flags: ['Inauthentic engagement', 'Bot-like interactions']
  },
  {
    key: 'tokenomics_red_flags',
    name: 'Tokenomics Red Flags',
    value: 68,
    score: 68,
    subline: 'Short vesting, high team allocation',
    flags: ['Excessive team allocation', 'Short vesting periods']
  },
];

// LOW RISK (PROCEED) EXAMPLE - DeFi Alpha Protocol
const proceedRawMetrics: RawMetricInput[] = [
  {
    key: 'team_identity',
    name: 'Team Identity',
    value: 8,
    score: 8,
    subline: 'Fully doxxed team with verified profiles',
    flags: []
  },
  {
    key: 'team_competence',
    name: 'Team Competence',
    value: 12,
    score: 12,
    subline: 'Proven track record, excellent documentation',
    flags: []
  },
  {
    key: 'contaminated_network',
    name: 'Contaminated Network',
    value: 5,
    score: 5,
    subline: 'Clean network, reputable associations',
    flags: []
  },
  {
    key: 'mercenary_keywords',
    name: 'Mercenary Keywords',
    value: 15,
    score: 15,
    subline: 'Healthy balance: 20% mercenary, 40% genuine, 40% technical',
    flags: []
  },
  {
    key: 'message_time_entropy',
    name: 'Message Time Entropy',
    value: 22,
    score: 22,
    subline: 'Natural posting patterns, high entropy',
    flags: []
  },
  {
    key: 'account_age_entropy',
    name: 'Account Age Entropy',
    value: 18,
    score: 18,
    subline: 'Organic growth over time',
    flags: []
  },
  {
    key: 'tweet_focus',
    name: 'Tweet Focus',
    value: 65,
    score: 65,
    subline: 'Balanced content mix',
    flags: []
  },
  {
    key: 'github_authenticity',
    name: 'GitHub Authenticity',
    value: 12,
    score: 12,
    subline: 'Original codebase, active development',
    flags: []
  },
  {
    key: 'bus_factor',
    name: 'Bus Factor',
    value: 25,
    score: 25,
    subline: 'Distributed contributions across team',
    flags: []
  },
  {
    key: 'artificial_hype',
    name: 'Artificial Hype',
    value: 18,
    score: 18,
    subline: 'Organic growth pattern',
    flags: []
  },
  {
    key: 'founder_distraction',
    name: 'Founder Distraction',
    value: 15,
    score: 15,
    subline: 'Focused on building, minimal external activities',
    flags: []
  },
  {
    key: 'engagement_authenticity',
    name: 'Engagement Authenticity',
    value: 20,
    score: 20,
    subline: 'Genuine conversations, deep threads',
    flags: []
  },
  {
    key: 'tokenomics_red_flags',
    name: 'Tokenomics Red Flags',
    value: 10,
    score: 10,
    subline: 'Fair distribution, long vesting',
    flags: []
  },
];

// MEDIUM RISK (FLAG) EXAMPLE - TokenSwap Pro
const flagRawMetrics: RawMetricInput[] = [
  {
    key: 'team_identity',
    name: 'Team Identity',
    value: 52,
    score: 52,
    subline: 'Mixed team - some doxxed, some anonymous',
    flags: ['Partial anonymity', 'Inconsistent professional profiles']
  },
  {
    key: 'team_competence',
    name: 'Team Competence',
    value: 48,
    score: 48,
    subline: 'Moderate experience, adequate documentation',
    flags: ['Limited track record', 'Basic documentation']
  },
  {
    key: 'contaminated_network',
    name: 'Contaminated Network',
    value: 45,
    score: 45,
    subline: 'Some questionable associations',
    flags: ['Minor agency concerns', 'Mixed advisor history']
  },
  {
    key: 'mercenary_keywords',
    name: 'Mercenary Keywords',
    value: 55,
    score: 55,
    subline: 'Elevated mercenary discourse (42%)',
    flags: ['High financial focus', 'Limited technical discussion']
  },
  {
    key: 'message_time_entropy',
    name: 'Message Time Entropy',
    value: 38,
    score: 38,
    subline: 'Some coordination patterns',
    flags: ['Suspicious timing patterns', 'Moderate bot activity']
  },
  {
    key: 'account_age_entropy',
    name: 'Account Age Entropy',
    value: 42,
    score: 42,
    subline: 'Moderate clustering',
    flags: ['Some bulk creation', 'Mixed account ages']
  },
  {
    key: 'tweet_focus',
    name: 'Tweet Focus',
    value: 58,
    score: 58,
    subline: 'Some topic drift',
    flags: ['Inconsistent messaging', 'Moderate pivot frequency']
  },
  {
    key: 'github_authenticity',
    name: 'GitHub Authenticity',
    value: 52,
    score: 52,
    subline: 'Some originality, moderate activity',
    flags: ['Partially forked code', 'Moderate development pace']
  },
  {
    key: 'bus_factor',
    name: 'Bus Factor',
    value: 45,
    score: 45,
    subline: 'Moderate dependency',
    flags: ['Limited contributor diversity', 'Moderate centralization']
  },
  {
    key: 'artificial_hype',
    name: 'Artificial Hype',
    value: 48,
    score: 48,
    subline: 'Some campaign activity',
    flags: ['Minor paid promotion', 'Moderate growth spikes']
  },
  {
    key: 'founder_distraction',
    name: 'Founder Distraction',
    value: 52,
    score: 52,
    subline: 'Some external commitments',
    flags: ['Moderate advisor roles', 'Some speaking circuit activity']
  },
  {
    key: 'engagement_authenticity',
    name: 'Engagement Authenticity',
    value: 45,
    score: 45,
    subline: 'Mixed authenticity',
    flags: ['Some copy-pasta content', 'Moderate bot presence']
  },
  {
    key: 'tokenomics_red_flags',
    name: 'Tokenomics Red Flags',
    value: 58,
    score: 58,
    subline: 'Some concerning allocations',
    flags: ['Elevated team allocation', 'Moderate vesting concerns']
  },
];

export const rejectExample: VerdictData = buildVerdictData(
  'MoonDoge Protocol',
  '@moondoge_protocol',
  rejectRawMetrics
);

export const proceedExample: VerdictData = buildVerdictData(
  'DeFi Alpha Protocol',
  'https://github.com/defialpha/core',
  proceedRawMetrics
);

export const flagExample: VerdictData = buildVerdictData(
  'TokenSwap Pro',
  'tokenswappro.xyz',
  flagRawMetrics
);

export const getPlaceholderData = (input: string): VerdictData => {
  const lowerInput = input.toLowerCase();

  // Return REJECT example for suspicious-looking inputs
  if (
    lowerInput.includes('moon') ||
    lowerInput.includes('doge') ||
    lowerInput.includes('rocket') ||
    lowerInput.includes('inu') ||
    lowerInput.includes('safe') ||
    lowerInput.includes('baby') ||
    lowerInput.includes('elon') ||
    lowerInput.includes('memecoin')
  ) {
    return buildVerdictData(
      input.replace(/[@/]/g, '').slice(0, 30) || 'Suspicious Project',
      input,
      rejectRawMetrics
    );
  }

  // Return PROCEED example for established-looking inputs
  if (
    lowerInput.includes('aave') ||
    lowerInput.includes('defi') ||
    lowerInput.includes('alpha') ||
    lowerInput.includes('protocol') ||
    lowerInput.includes('uniswap') ||
    lowerInput.includes('compound') ||
    lowerInput.includes('maker')
  ) {
    return buildVerdictData(
      input.replace(/[@/]/g, '').slice(0, 30) || 'Legitimate Project',
      input,
      proceedRawMetrics
    );
  }

  // Return FLAG example for ambiguous inputs
  if (
    lowerInput.includes('swap') ||
    lowerInput.includes('token') ||
    lowerInput.includes('bridge') ||
    lowerInput.includes('vault') ||
    lowerInput.includes('yield')
  ) {
    return buildVerdictData(
      input.replace(/[@/]/g, '').slice(0, 30) || 'Mixed Signals Project',
      input,
      flagRawMetrics
    );
  }

  // For other inputs, randomly choose based on weighted probability
  const rand = Math.random();
  let rawMetrics;
  
  if (rand < 0.5) {
    // 50% chance of REJECT (high-risk demo)
    rawMetrics = rejectRawMetrics;
  } else if (rand < 0.7) {
    // 20% chance of FLAG
    rawMetrics = flagRawMetrics;
  } else {
    // 30% chance of PROCEED
    rawMetrics = proceedRawMetrics;
  }

  return buildVerdictData(
    input.replace(/[@/]/g, '').slice(0, 30) || 'Unknown Project',
    input,
    rawMetrics
  );
};

// Helper function to get detailed metric explanations
export const getMetricExplanation = (key: string): { title: string; description: string; weight: number } => {
  const metric = METRIC_WEIGHTS.find(m => m.key === key);
  if (!metric) return { title: 'Unknown', description: 'Metric not found', weight: 0 };

  const explanations: Record<string, { title: string; description: string }> = {
    team_identity: {
      title: 'Team Identity',
      description: 'Measures institutional legitimacy - are these real people with reputations at stake? Assesses LinkedIn profiles, GitHub history, Twitter verification, professional photos, and public information.'
    },
    team_competence: {
      title: 'Team Competence',
      description: 'Evaluates human capital - technical ability, track record, and institutional knowledge codification. Includes GitHub reputation, past project outcomes, technical publications, and documentation quality.'
    },
    contaminated_network: {
      title: 'Contaminated Network',
      description: 'Detects professional scam infrastructure - agencies, advisors, and influencers with rug histories. Checks against proprietary reputation database for cross-project pattern tracking.'
    },
    mercenary_keywords: {
      title: 'Mercenary Keywords',
      description: 'Analyzes financialization vs. authentic community vs. technical discourse balance. Uses three-tier weighted keyword categorization with context-aware NLP (BERT sentiment analysis).'
    },
    message_time_entropy: {
      title: 'Message Time Entropy',
      description: 'Measures temporal organization - natural vs. coordinated posting patterns using Shannon entropy. Detects bot-like scheduling, timezone distribution, and burst patterns.'
    },
    account_age_entropy: {
      title: 'Account Age Entropy',
      description: 'Assesses network formation authenticity - organic growth vs. Sybil attacks. Analyzes account creation date distribution and detects bulk creation patterns.'
    },
    tweet_focus: {
      title: 'Tweet Focus',
      description: 'Evaluates discursive coherence - consistent messaging vs. scattered topics. Uses topic modeling (LDA) and narrative concentration analysis.'
    },
    github_authenticity: {
      title: 'GitHub Authenticity',
      description: 'Measures real development vs. theater. Analyzes fork originality, commit patterns, contributor diversity, issue/PR engagement, and code quality indicators.'
    },
    bus_factor: {
      title: 'Bus Factor',
      description: 'Assesses single point of failure risk - project dependency on few individuals. Analyzes technical contribution concentration, community management distribution, and social media management.'
    },
    artificial_hype: {
      title: 'Artificial Hype',
      description: 'Detects attention economy manipulation - sudden bursts vs. organic growth. Uses statistical spike detection, retention rate analysis, and campaign timing coordination.'
    },
    founder_distraction: {
      title: 'Founder Distraction',
      description: 'Measures role conflict in digital entrepreneurship - whether founders are focused on building or being influencers/serial entrepreneurs. Analyzes Twitter activity, speaking circuits, and concurrent projects.'
    },
    engagement_authenticity: {
      title: 'Engagement Authenticity',
      description: 'Evaluates genuine vs. transactional sociality - whether community engagement is real or incentivized performance. Uses MinHash for copy-pasta detection and thread depth analysis.'
    },
    tokenomics_red_flags: {
      title: 'Tokenomics Red Flags',
      description: 'Identifies economic structure warning signs - allocation, vesting, liquidity provisions indicating rug potential. Handles non-disclosure gracefully with confidence scoring.'
    }
  };

  return {
    title: metric.name,
    description: explanations[key]?.description || 'No description available',
    weight: metric.weight
  };
};